// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/pijalu/go.hands.two/frinsultproto/frinsult.proto

package frinsultproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Frinsult struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	Score                int64    `protobuf:"varint,3,opt,name=Score,proto3" json:"Score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frinsult) Reset()         { *m = Frinsult{} }
func (m *Frinsult) String() string { return proto.CompactTextString(m) }
func (*Frinsult) ProtoMessage()    {}
func (*Frinsult) Descriptor() ([]byte, []int) {
	return fileDescriptor_frinsult_aa152e4e04890d85, []int{0}
}
func (m *Frinsult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frinsult.Unmarshal(m, b)
}
func (m *Frinsult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frinsult.Marshal(b, m, deterministic)
}
func (dst *Frinsult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frinsult.Merge(dst, src)
}
func (m *Frinsult) XXX_Size() int {
	return xxx_messageInfo_Frinsult.Size(m)
}
func (m *Frinsult) XXX_DiscardUnknown() {
	xxx_messageInfo_Frinsult.DiscardUnknown(m)
}

var xxx_messageInfo_Frinsult proto.InternalMessageInfo

func (m *Frinsult) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Frinsult) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Frinsult) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type Frinsults struct {
	Insults              []*Frinsult `protobuf:"bytes,1,rep,name=insults,proto3" json:"insults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Frinsults) Reset()         { *m = Frinsults{} }
func (m *Frinsults) String() string { return proto.CompactTextString(m) }
func (*Frinsults) ProtoMessage()    {}
func (*Frinsults) Descriptor() ([]byte, []int) {
	return fileDescriptor_frinsult_aa152e4e04890d85, []int{1}
}
func (m *Frinsults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frinsults.Unmarshal(m, b)
}
func (m *Frinsults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frinsults.Marshal(b, m, deterministic)
}
func (dst *Frinsults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frinsults.Merge(dst, src)
}
func (m *Frinsults) XXX_Size() int {
	return xxx_messageInfo_Frinsults.Size(m)
}
func (m *Frinsults) XXX_DiscardUnknown() {
	xxx_messageInfo_Frinsults.DiscardUnknown(m)
}

var xxx_messageInfo_Frinsults proto.InternalMessageInfo

func (m *Frinsults) GetInsults() []*Frinsult {
	if m != nil {
		return m.Insults
	}
	return nil
}

type ByIDRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByIDRequest) Reset()         { *m = ByIDRequest{} }
func (m *ByIDRequest) String() string { return proto.CompactTextString(m) }
func (*ByIDRequest) ProtoMessage()    {}
func (*ByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_frinsult_aa152e4e04890d85, []int{2}
}
func (m *ByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByIDRequest.Unmarshal(m, b)
}
func (m *ByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByIDRequest.Marshal(b, m, deterministic)
}
func (dst *ByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByIDRequest.Merge(dst, src)
}
func (m *ByIDRequest) XXX_Size() int {
	return xxx_messageInfo_ByIDRequest.Size(m)
}
func (m *ByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByIDRequest proto.InternalMessageInfo

func (m *ByIDRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type VoteRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Vote                 int64    `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteRequest) Reset()         { *m = VoteRequest{} }
func (m *VoteRequest) String() string { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()    {}
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_frinsult_aa152e4e04890d85, []int{3}
}
func (m *VoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRequest.Unmarshal(m, b)
}
func (m *VoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRequest.Marshal(b, m, deterministic)
}
func (dst *VoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRequest.Merge(dst, src)
}
func (m *VoteRequest) XXX_Size() int {
	return xxx_messageInfo_VoteRequest.Size(m)
}
func (m *VoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRequest proto.InternalMessageInfo

func (m *VoteRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *VoteRequest) GetVote() int64 {
	if m != nil {
		return m.Vote
	}
	return 0
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_frinsult_aa152e4e04890d85, []int{4}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Frinsult)(nil), "frinsultproto.Frinsult")
	proto.RegisterType((*Frinsults)(nil), "frinsultproto.Frinsults")
	proto.RegisterType((*ByIDRequest)(nil), "frinsultproto.ByIDRequest")
	proto.RegisterType((*VoteRequest)(nil), "frinsultproto.VoteRequest")
	proto.RegisterType((*Void)(nil), "frinsultproto.void")
}

func init() {
	proto.RegisterFile("github.com/pijalu/go.hands.two/frinsultproto/frinsult.proto", fileDescriptor_frinsult_aa152e4e04890d85)
}

var fileDescriptor_frinsult_aa152e4e04890d85 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0x29, 0xfd, 0x7e, 0x51, 0x06, 0x05, 0x33, 0x9a, 0xd8, 0x90, 0x98, 0x90, 0x3d, 0x71,
	0x5a, 0x02, 0x1e, 0x4d, 0xd4, 0x98, 0x55, 0xec, 0xb5, 0xa8, 0x77, 0x7e, 0x8c, 0x50, 0x83, 0xdd,
	0xda, 0xdd, 0xa2, 0xfe, 0x5f, 0xfe, 0x81, 0xa6, 0x2b, 0x95, 0x82, 0x2e, 0xf1, 0x36, 0xf3, 0xe6,
	0xe5, 0xbd, 0x4f, 0xb7, 0x70, 0x36, 0x0d, 0xf5, 0x2c, 0x1d, 0xf1, 0xb1, 0x7c, 0xee, 0xc4, 0xe1,
	0xd3, 0x70, 0x9e, 0x76, 0xa6, 0x92, 0xcf, 0x86, 0xd1, 0x44, 0x71, 0xfd, 0x2a, 0x3b, 0x8f, 0x49,
	0x18, 0xa9, 0x74, 0xae, 0xe3, 0x44, 0xea, 0xd5, 0xc6, 0xcd, 0x8a, 0xfb, 0x6b, 0x57, 0x26, 0x60,
	0xf7, 0x66, 0x29, 0x60, 0x1d, 0xca, 0xbe, 0xf0, 0x9c, 0x96, 0xd3, 0x76, 0x83, 0xb2, 0x2f, 0x10,
	0xe1, 0xdf, 0x1d, 0xbd, 0x69, 0xaf, 0xdc, 0x72, 0xda, 0xd5, 0xc0, 0xcc, 0x78, 0x04, 0xff, 0x07,
	0x63, 0x99, 0x90, 0xe7, 0x1a, 0xdb, 0xd7, 0xc2, 0xce, 0xa1, 0x9a, 0xa7, 0x28, 0xec, 0xc2, 0xce,
	0x72, 0xf4, 0x9c, 0x96, 0xdb, 0xae, 0xf5, 0x8e, 0xf9, 0x5a, 0x27, 0xcf, 0xad, 0x41, 0xee, 0x63,
	0x27, 0x50, 0xbb, 0x7a, 0xf7, 0x45, 0x40, 0x2f, 0x29, 0xa9, 0x1f, 0x20, 0xac, 0x0b, 0xb5, 0x07,
	0xa9, 0xc9, 0x72, 0xce, 0x38, 0x17, 0x52, 0x93, 0xe1, 0x74, 0x03, 0x33, 0xb3, 0x4a, 0xa6, 0x85,
	0x93, 0xde, 0x87, 0x0b, 0x8d, 0xbc, 0x6f, 0x40, 0xc9, 0x22, 0x1c, 0x13, 0xde, 0x42, 0xa3, 0x4f,
	0x3a, 0x57, 0xb3, 0x62, 0x6c, 0x6e, 0x20, 0x16, 0x68, 0x9a, 0x36, 0x7c, 0x56, 0xc2, 0x3e, 0xa0,
	0xa0, 0x39, 0x69, 0xfa, 0x73, 0xd8, 0xe1, 0xc6, 0x2d, 0x83, 0x64, 0x25, 0x14, 0x50, 0xf7, 0x23,
	0x45, 0xc9, 0x37, 0x15, 0xda, 0x5a, 0xb7, 0xe1, 0x5c, 0x42, 0xfd, 0x3e, 0x9e, 0x0c, 0x57, 0x38,
	0xf6, 0x14, 0x0b, 0xc7, 0x35, 0x1c, 0x64, 0x2f, 0xbd, 0xf5, 0x73, 0x0a, 0xbf, 0xc2, 0x16, 0x73,
	0x01, 0x7b, 0x85, 0x17, 0x56, 0xf8, 0x9b, 0xad, 0xe9, 0x59, 0xd8, 0x14, 0x2b, 0x8d, 0x2a, 0x46,
	0x3a, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x88, 0x50, 0x4b, 0x24, 0xeb, 0x02, 0x00, 0x00,
}
